CC = gcc
BIN_NAME = CMP
SRC_NAME = main.c i_type.c r_type.c j_type.c memory.c

${BIN_NAME}: ${SRC_NAME}
	${CC} -g -o ${BIN_NAME} ${SRC_NAME} -lm

clean:
	rm -f *.o
	rm -f *.rpt
	rm -f *.txt
	rm -f CMP
