CC = gcc
BIN_NAME = single_cycle 
SRC_NAME = main.c i_type.c r_type.c j_type.c

${BIN_NAME}: ${SRC_NAME}
	${CC} -g -o ${BIN_NAME} ${SRC_NAME} -lm

clean:
	rm -f *.o
	rm -f *.rpt
	rm -f *.txt
	rm -f single_cycle
